// Roblox Limiteds - Items Definition

export const items = [
  {
    id: 'golden_fedora',
    name: 'Golden Fedora',
    startingRAP: 500,
    rap: 2500,
    salesVolume: [],
    stock: 10,
    maxStock: 16,
    tags: ['demand'],
    image: 'golden_fedora.png',
    description: 'A shiny gold feodra',
    chart: [],
  },
  {
    id: 'blue_sparkle_time',
    name: 'Blue Sparkle Time Fedora',
    startingRAP: 1000,
    rap: 9700,
    salesVolume: [],
    stock: 3,
    maxStock: 16,
    tags: ['rare'],
    image: 'blue_sparkle.png',
    description: 'Ultra-rare sparkle time fedora',
    chart: [],
  },
  {
    id: 'emerald_valk',
    name: 'Emerald Valkyrie',
    startingRAP: 900,
    rap: 3000,
    salesVolume: [],
    stock: 8,
    maxStock: 16,
    tags: ['demand'],
    image: 'emerald_valk.png',
    description: 'In high demand for its unique style.',
    chart: [],
  },
  {
    id: 'sinister_branch',
    name: 'Sinister Branches',
    startingRAP: 200,
    rap: 250,
    salesVolume: [],
    stock: 16,
    maxStock: 16,
    tags: [],
    image: 'sinister_branch.png',
    description: 'A common limited item.',
    chart: [],
  },
  {
    id: 'classic_roblox',
    name: 'Classic Roblox Fedora',
    startingRAP: 750,
    rap: 12050,
    salesVolume: [],
    stock: 2,
    maxStock: 16,
    tags: ['rare'],
    image: 'classic_fedora.png',
    description: 'A nostalgic and rare item.',
    chart: [],
  },
   {
    id: 'sinister_pump',
    name: 'Sinister P',
    startingRAP: 250,
    rap: 2222,
    salesVolume: [],
    stock: 9,
    maxStock: 16,
    tags: ['demand'],
    image: 'sinister_p.png',
    description: 'A nostalgic and demand item',
    chart: [],
  },
  // Add your own:
  // {
  //   id: '',
  //   name: '',
  //   startingRAP: 0,
  //   rap: 0,
  //   salesVolume: [],
  //   stock: 0,
  //   maxStock: 16,
  //   tags: [],
  //   image: '',
  //   description: '',
  //   chart: [],
  // },
  // {
  //   id: '',
  //   name: '',
  //   startingRAP: 0,
  //   rap: 0,
  //   salesVolume: [],
  //   stock: 0,
  //   maxStock: 16,
  //   tags: [],
  //   image: '',
  //   description: '',
  //   chart: [],
  // },
];
